version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    command: ["streamlit", "run", "app.py"]
